spring.application.name=ads-backend

# SQLite-Datenbankverbindung
server.port=8080
spring.datasource.url=jdbc:sqlite:database.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.datasource.username=
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update

# Fester Upload-Pfad (statt Temp)
upload.path=C:/Users/tomsc/Desktop/uploads


# Verhindere, dass Tomcat Dateien im Temp-Ordner speichert
spring.servlet.multipart.location=C:/Users/tomsc/Desktop/uploads/temp

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=10MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=DEBUG
spring.web.resources.static-locations=file:///C:/Users/tomsc/Desktop/uploads/



